# Generated by Django 6.0.6 on 2026-07-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='short_code',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
