# Generated by Django 6.0.7 on 2026-07-27 06:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(blank=True, max_length=150)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('passkey', models.CharField(blank=True, default='', max_length=8)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('short_line', models.CharField(blank=True, max_length=300)),
                ('letter', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Classic Gift',
                'verbose_name_plural': 'Classic Gifts',
            },
        ),
    ]
