# Generated by Django 6.0.6 on 2026-07-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic', '0002_gift_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='short_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
